name: Claude Code PR Review

on:
  pull_request:
    types: [ opened ]
  issue_comment: # issue または PR のコメントを指す。PR も内部的には Issue 扱い
    types: [ created ] # 新規コメントでのみトリガー。編集や削除はスルー
  pull_request_review_comment: # Files changed タブの行コメント
    types: [ created ]
  issues:
    types: [ opened ]

permissions:
  contents: write # 権限が強いので、main ブランチの同ymlファイルと完全一致していないと動かない！
  pull-requests: write
  issues: write
  id-token: write

env:
  ALLOWED_AUTHOR_ASSOCIATIONS: '["OWNER","MEMBER","COLLABORATOR"]'

jobs:
  # プルリクエストでの自動レビュー
  auto-review:
    # PR作成者が外部ユーザーの場合と、fork由来のPRでは実行されない
    if: |
      github.event_name == 'pull_request' &&
      contains(fromJSON(env.ALLOWED_AUTHOR_ASSOCIATIONS), github.event.pull_request.author_association) &&
      github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # PR の差分ファイルまで取得する

      - name: Run Claude Code Review
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # /review だけだとPRコメントじゃなくてサマリーだけに結果が出力されたため、プロンプトを追加
          prompt: |
            /review
            
            Please review the changes in this pull request and post your review results as comments on this pull request in japanese.
          # Bash 経由で `gh pr list` を呼ぶため、Bash ツールを明示的に許可する
          claude_args: | 
            --model claude-sonnet-4-5-20250929
            --system-prompt "Please speak in Japanese."
            --allowedTools Bash,Github

  # @claude とコメントすると走る
  call-claude:
    if: |
      (
        (github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment') &&
        contains(github.event.comment.body, '@claude') &&
        contains(fromJSON(env.ALLOWED_AUTHOR_ASSOCIATIONS), github.event.comment.author_association)
      ) ||
      (
        github.event_name == 'issues' &&
        contains(github.event.issue.body, '@claude') &&
        contains(fromJSON(env.ALLOWED_AUTHOR_ASSOCIATIONS), github.event.issue.author_association)
      )

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Claude Code Review when calling
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args: |
            --model claude-sonnet-4-5-20250929
            --system-prompt "Please speak in Japanese."
            --allowedTools Bash,Github
